{ config, pkgs, modulesPath, ... }:
{
  nix.settings.experimental-features = "nix-command flakes";
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      ./incus.nix
      # Include the OrbStack-specific configuration.
      ./orbstack.nix
    ];

  time.timeZone = "Europe/Berlin";

  users.defaultUserShell = pkgs.zsh;
  users.users.mz = {
    uid = 501;
    extraGroups = [ "wheel" ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/mz";
    homeMode = "700";
    useDefaultShell = true;

    packages = with pkgs; [
      clang
      zig
    ];
  };
  users.mutableUsers = false;

  security.sudo.wheelNeedsPassword = false;

  programs = {
    direnv.enable = true;
    zsh = {
      enable = true;
      enableCompletion = true;
      autosuggestions.enable = true;
    };
    tmux = import ../../shared/tmux.nix;
    neovim = {
      enable = true;
      defaultEditor = true;
    };
    gnupg.agent = {
      enable = true;
      enableSSHSupport = true;
    };
  };
  environment.systemPackages = import ../../shared/packages.nix { inherit pkgs; };

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
      -----BEGIN CERTIFICATE-----
MIICDDCCAbKgAwIBAgIQNLSGY1wP99mhduXl4edifDAKBggqhkjOPQQDAjBmMR0w
GwYDVQQKExRPcmJTdGFjayBEZXZlbG9wbWVudDEeMBwGA1UECwwVQ29udGFpbmVy
cyAmIFNlcnZpY2VzMSUwIwYDVQQDExxPcmJTdGFjayBEZXZlbG9wbWVudCBSb290
IENBMB4XDTI0MDEwODEwNTQyM1oXDTM0MDEwODEwNTQyM1owZjEdMBsGA1UEChMU
T3JiU3RhY2sgRGV2ZWxvcG1lbnQxHjAcBgNVBAsMFUNvbnRhaW5lcnMgJiBTZXJ2
aWNlczElMCMGA1UEAxMcT3JiU3RhY2sgRGV2ZWxvcG1lbnQgUm9vdCBDQTBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABDBqQSngvu6NvjfO+hbf+Q2u2/5/azYpzVyt
74v/B9o5pLrz7SIaAuKP6gddDBAYqWUZX0jjp7Ha1kbBE4t8SEOjQjBAMA4GA1Ud
DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBT4JtmGfbigdJPQ
q4OhHojZLWgjOjAKBggqhkjOPQQDAgNIADBFAiEA4Y+4Ma+A2lgZU73BZSRFWUmH
KECBeuLjkwIBt3VLlnQCIDigjLmZ0mR4rEbnjxomiQijVjjflX9a3gfnep+hX/Az
-----END CERTIFICATE-----

    ''
  ];

  system.stateVersion = "25.05";
}
